services:
  nginx:
    image: "nginx:alpine"
    volumes:
      - "./public:/wsc"
      - "./docker/nginx/realip.conf:/etc/nginx/conf.d/realip.conf"
      - "./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "${FPM_PORT:-80}:80"
    networks:
      - wsc-network

  php-fpm:
    build:
      context: docker/php-fpm
      args:
        PHP_VERSION: "${PHP_VERSION:-8.2}"
    environment:
      WSC_VERSION: "${WSC_VERSION:-6.1}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-woltlab_suite}"
      MYSQL_USER: "${MYSQL_USER:-woltlab_suite}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-woltlab_suite}"
    volumes:
      - "./public:/wsc"
      - "./devtools:/devtools"
      - "./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini"
      - "./docker/php-fpm/WCFSetupTemplate.conf:/usr/local/etc/php-fpm.d/WCFSetupTemplate.conf"
    networks:
      - wsc-network

  mysql:
    image: "mariadb:lts"
    volumes:
      - "./docker/mysql/conf/my.cnf:/etc/mysql/my.cnf:ro"
    environment:
      MYSQL_ROOT_HOST: 172.*.*.*
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-woltlab_suite}"
      MYSQL_USER: "${MYSQL_USER:-woltlab_suite}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-woltlab_suite}"
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - wsc-network

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:ubuntu
    ulimits:
      memlock: -1
    volumes:
      - "dragonflydata:/data"
    networks:
      - wsc-network

networks:
  wsc-network:
    driver: bridge

volumes:
  dragonflydata:
